version: '3.7'
services:
    db_service:
      container_name: db_service
      image: mariadb:10.3
      restart: "no"
      environment:
          MYSQL_ROOT_PASSWORD: 123456
# if the default ports changed then we need to use this port number with server ip example 12.0.0.1:3307
      ports:
          - 3307:3306

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: "no"
      ports:
          - 13000:80
      environment:
          - PMA_ARBITRARY=1

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
         - "8090:80"
      volumes:
         - .:/var/www/symfony_with_docker
         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - db_service
         - phpmyadmin

    php:
      container_name: php
      build:
        context: ./docker/php
      volumes:
         - .:/var/www/symfony_with_docker
      ports:
         - "19000:9000"
  
    beanstalkd:
      image: schickling/beanstalkd
      command: [ '-b', '/var/beanstalkd', '-V' ]
      ports:
         - 11300:11300
      volumes:
         - ./var/beanstalkd:/var/beanstalkd